# Generated by Django 2.1.2 on 2018-10-28 22:33

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('intent', models.CharField(max_length=128)),
                ('phrases', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=256))),
                ('answers', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=256))),
            ],
        ),
        migrations.CreateModel(
            name='NLUModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='intent',
            name='nlu_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='arclight.NLUModel'),
        ),
    ]
