# Generated by Django 2.1.2 on 2018-10-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arclight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlumodel',
            name='model_directory',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
