# Generated by Django 2.1.2 on 2018-10-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arclight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intent',
            old_name='intent',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='intent',
            name='nlu_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='arclight.NLUModel'),
        ),
        migrations.AlterField(
            model_name='nlumodel',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
